### ISSUE TITLE
Why is `react` not a dev dependency?

### ISSUE THREAD

**Issue by PaulRBerg** [Timonwa/demo-ui-library#2]
Thanks for sharing this template and the [accompanying article](https://blog.logrocket.com/how-to-build-component-library-react-typescript/).

Could you dive into a little bit more detail about why `react` is only a peer dependency, and not a dev dependency, too?

https://github.com/Timonwa/demo-ui-library/blob/main/package.json#L62-L65

It looks like React is imported in the actual code - doesn't this mean that it should be a dev dependency?

https://github.com/Timonwa/demo-ui-library/blob/d5fee046af2d0975830be54962bc20fc5a35400d/src/components/Button/Button.tsx#L1

Based on [this StackOverflow answer](https://stackoverflow.com/a/30454133/3873510), I would be inclined to believe that `react` should be added in `devDependencies`.

_Side note_: would you like to enable [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) in this repository? I would have created a discussion instead of a repo.

**Comment by Timonwa** [comment]
Hi @PaulRBerg. Thanks for your feedback! React is listed as a peer dependency in the package.json because the library assumes the consuming project already has React installed. This allows flexibility in choosing the React version. The import statement in the code doesn't necessarily mean React should be a dev dependency. Regarding GitHub Discussions, it's a great idea to enable it for more interactive discussions. Please let me know if you have further questions. Thanks!

**Comment by PaulRBerg** [comment]
Thanks for confirming @Timonwa. I'll close this issue.
